title: Zephyr Tutorial
remote_theme: bedroesb/just-the-docs

# baseurl: "/zephyr-rtos-tutorial"

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-seo-tag

callouts:
  note:
    title: Note
    color: green
  warning:
    title: Warning
    color: yellow
  error:
    title: Error
    color: red
